In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
%pwd

'F:\\neel\\fingertips\\python\\jupyternotbook'

In [4]:
data = pd.read_csv("NYC.csv")

In [4]:
data

,Survey,Question,Year,Prevalence,Lower95%CI,Upper95%CI
0,CHS,Health Insurance Coverage,2014,86.2,85.2,87.2
1,CHS,Health Insurance Coverage,2011,81.4,79.7,83.0
2,CHS,Binge Drinking,2011,17.9,16.4,19.6
3,CHS,Binge Drinking,2011,17.9,16.4,19.6
4,CHS,No Personal Doctor,2010,NaN,NaN,NaN
...,...,...,...,...,...,...
95,CHS,"Colon cancer screening, adults age 50+ (colono...",2010,67.5,65.4,69.4
96,CHS,No Personal Doctor,2012,18.3,17.0,19.7
97,CHS,Did not get needed medical care,2014,9.6,8.7,10.5
98,CHS,Health Insurance Coverage,2012,80.2,78.7,81.5
99,CHS,"Flu shot in last 12 months, adults ages 65+ (n...",2011,67.4,63.9,70.7

1) Get first 5 rows of the dataset.

In [5]:
data.head()

  Survey                   Question  Year  Prevalence  Lower95%CI  Upper95%CI
0    CHS  Health Insurance Coverage  2014        86.2        85.2        87.2
1    CHS  Health Insurance Coverage  2011        81.4        79.7        83.0
2    CHS             Binge Drinking  2011        17.9        16.4        19.6
3    CHS             Binge Drinking  2011        17.9        16.4        19.6
4    CHS         No Personal Doctor  2010         NaN         NaN         NaN

2) Get first 25 rows of the dataset.

In [6]:
data.head(25)

,Survey,Question,Year,Prevalence,Lower95%CI,Upper95%CI
0,CHS,Health Insurance Coverage,2014,86.2,85.2,87.2
1,CHS,Health Insurance Coverage,2011,81.4,79.7,83.0
2,CHS,Binge Drinking,2011,17.9,16.4,19.6
3,CHS,Binge Drinking,2011,17.9,16.4,19.6
4,CHS,No Personal Doctor,2010,NaN,NaN,NaN
5,CHS,"Colon cancer screening, adults age 50+ (colono...",2011,68.6,66.2,70.8
6,CHS,Obesity,2014,24.7,23.4,26.0
7,CHS,No Personal Doctor,2013,19.1,18.0,20.3
8,CHS,Self-reported Health Status (excellent/very go...,2010,79.1,77.8,80.3
9,CHS,Drinks 1 or more sugar-sweetened beverages per...,2013,23.3,22.1,24.6
10,CHS,"Flu shot in last 12 months, adults ages 65+ (n...",2014,64.2,60.7,67.6
11,CHS,Did not get needed medical care,2012,11.1,10.1,12.2
12,CHS,Drinks 1 or more sugar-sweetened beverages per...,2010,30.3,28.8,31.8
13,CHS,Self-reported Health Status (excellent/very go...,2011,78.2,76.7,79.6
14,CHS,Smoking Status (current smokers),2013,16.1,15.0,17.2
15,CHS,Health Insurance Coverage,2013,79.1,77.8,80.3
16,CHS,Smoking Status (current smokers),2014,13.9,12.8,14.9
17,CHS,Obesity,2014,24.7,23.4,26.0
18,CHS,"Flu shot in last 12 months, adults ages 65+ (n...",2012,61.8,58.5,64.9
19,CHS,Obesity,2013,23.4,22.2,24.7
20,CHS,"Flu shot in last 12 months, adults ages 65+ (n...",2013,66.8,63.7,69.8
21,CHS,Self-reported Health Status (excellent/very go...,2014,77.8,76.6,78.9
22,CHS,No Personal Doctor,2010,NaN,NaN,NaN
23,CHS,Health Insurance Coverage,2014,86.2,85.2,87.2
24,CHS,Obesity,2012,24.2,22.8,25.5

3) Get the dataset from row 50.

In [7]:
data[50::]

,Survey,Question,Year,Prevalence,Lower95%CI,Upper95%CI
50,CHS,Self-reported Health Status (excellent/very go...,2013,76.9,75.7,78.0
51,CHS,No Personal Doctor,2011,16.9,15.5,18.5
52,CHS,Health Insurance Coverage,2010,83.3,82.0,84.6
53,CHS,Drinks 1 or more sugar-sweetened beverages per...,2014,22.5,21.2,23.8
54,CHS,"Flu shot in last 12 months, adults ages 65+ (n...",2012,61.8,58.5,64.9
55,CHS,"Colon cancer screening, adults age 50+ (colono...",2012,68.5,66.3,70.5
56,CHS,Health Insurance Coverage,2013,79.1,77.8,80.3
57,CHS,Self-reported Health Status (excellent/very go...,2010,79.1,77.8,80.3
58,CHS,"Flu shot in last 12 months, adults ages 65+ (n...",2013,66.8,63.7,69.8
59,CHS,Binge Drinking,2010,NaN,NaN,NaN
60,CHS,Smoking Status (current smokers),2012,15.5,14.4,16.8
61,CHS,"Colon cancer screening, adults age 50+ (colono...",2013,69.0,67.0,71.0
62,CHS,Self-reported Health Status (excellent/very go...,2011,78.2,76.7,79.6
63,CHS,Did not get needed medical care,2011,10.7,9.6,12.0
64,CHS,No Personal Doctor,2013,19.1,18.0,20.3
65,CHS,Binge Drinking,2014,16.5,15.4,17.7
66,CHS,Drinks 1 or more sugar-sweetened beverages per...,2012,28.2,26.7,29.6
67,CHS,Health Insurance Coverage,2010,83.3,82.0,84.6
68,CHS,Obesity,2011,23.7,22.2,25.3
69,CHS,Self-reported Health Status (excellent/very go...,2013,76.9,75.7,78.0
70,CHS,Drinks 1 or more sugar-sweetened beverages per...,2012,28.2,26.7,29.6
71,CHS,"Flu shot in last 12 months, adults ages 65+ (n...",2010,62.3,59.4,65.1
72,CHS,Self-reported Health Status (excellent/very go...,2012,78.7,77.5,79.9
73,CHS,"Flu shot in last 12 months, adults ages 65+ (n...",2014,64.2,60.7,67.6
74,CHS,Binge Drinking,2012,19.6,18.2,20.9
75,CHS,"Colon cancer screening, adults age 50+ (colono...",2012,68.5,66.3,70.5
76,CHS,Health Insurance Coverage,2011,81.4,79.7,83.0
77,CHS,Smoking Status (current smokers),2012,15.5,14.4,16.8
78,CHS,Smoking Status (current smokers),2011,14.8,13.5,16.3
79,CHS,Did not get needed medical care,2012,11.1,10.1,12.2
80,CHS,Did not get needed medical care,2013,11.2,10.3,12.2
81,CHS,"Colon cancer screening, adults age 50+ (colono...",2014,69.9,67.8,72.0
82,CHS,Drinks 1 or more sugar-sweetened beverages per...,2013,23.3,22.1,24.6
83,CHS,No Personal Doctor,2012,18.3,17.0,19.7
84,CHS,Drinks 1 or more sugar-sweetened beverages per...,2010,30.3,28.8,31.8
85,CHS,Smoking Status (current smokers),2014,13.9,12.8,14.9
86,CHS,Did not get needed medical care,2014,9.6,8.7,10.5
87,CHS,"Colon cancer screening, adults age 50+ (colono...",2011,68.6,66.2,70.8
88,CHS,No Personal Doctor,2011,16.9,15.5,18.5
89,CHS,Obesity,2010,23.4,22.1,24.8
90,CHS,Did not get needed medical care,2011,10.7,9.6,12.0
91,CHS,Obesity,2012,24.2,22.8,25.5
92,CHS,"Colon cancer screening, adults age 50+ (colono...",2010,67.5,65.4,69.4
93,CHS,Did not get needed medical care,2010,10.3,9.4,11.4
94,CHS,No Personal Doctor,2014,15.6,14.5,16.7
95,CHS,"Colon cancer screening, adults age 50+ (colono...",2010,67.5,65.4,69.4
96,CHS,No Personal Doctor,2012,18.3,17.0,19.7
97,CHS,Did not get needed medical care,2014,9.6,8.7,10.5
98,CHS,Health Insurance Coverage,2012,80.2,78.7,81.5
99,CHS,"Flu shot in last 12 months, adults ages 65+ (n...",2011,67.4,63.9,70.7

4) Get the first 3 rows and 5 columns from the dataset .

In [11]:
data.head()

  Survey                   Question  Year  Prevalence  Lower95%CI  Upper95%CI
0    CHS  Health Insurance Coverage  2014        86.2        85.2        87.2
1    CHS  Health Insurance Coverage  2011        81.4        79.7        83.0
2    CHS             Binge Drinking  2011        17.9        16.4        19.6
3    CHS             Binge Drinking  2011        17.9        16.4        19.6
4    CHS         No Personal Doctor  2010         NaN         NaN         NaN

In [12]:
data.iloc[0:3,0:5]

  Survey                   Question  Year  Prevalence  Lower95%CI
0    CHS  Health Insurance Coverage  2014        86.2        85.2
1    CHS  Health Insurance Coverage  2011        81.4        79.7
2    CHS             Binge Drinking  2011        17.9        16.4

5) Display the Question answered by the first 7 rows of the dataset.

In [11]:
data['Question'].head(7).unique()

array(['Health Insurance Coverage', 'Binge Drinking',
       'No Personal Doctor',
       'Colon cancer screening, adults age 50+ (colonoscopy)', 'Obesity'],
      dtype=object)

6) Get the data for rows 0,10,99 from the dataset.

In [14]:
list1 = [0,10,99]
data.loc[list1,:]

,Survey,Question,Year,Prevalence,Lower95%CI,Upper95%CI
0,CHS,Health Insurance Coverage,2014,86.2,85.2,87.2
10,CHS,"Flu shot in last 12 months, adults ages 65+ (n...",2014,64.2,60.7,67.6
99,CHS,"Flu shot in last 12 months, adults ages 65+ (n...",2011,67.4,63.9,70.7

7) Display Question, Year, Prevalence for all the rows in the dataset.

In [16]:
data.loc[:,['Question','Year','Prevalence']]

                                             Question  Year  Prevalence
0                           Health Insurance Coverage  2014        86.2
1                           Health Insurance Coverage  2011        81.4
2                                      Binge Drinking  2011        17.9
3                                      Binge Drinking  2011        17.9
4                                  No Personal Doctor  2010         NaN
..                                                ...   ...         ...
95  Colon cancer screening, adults age 50+ (colono...  2010        67.5
96                                 No Personal Doctor  2012        18.3
97                    Did not get needed medical care  2014         9.6
98                          Health Insurance Coverage  2012        80.2
99  Flu shot in last 12 months, adults ages 65+ (n...  2011        67.4

[100 rows x 3 columns]

8) Display Lower95%CI, Upper95%CI, for all the rows in the dataset.

In [17]:
data.loc[:,['Lower95%CI','Upper95%CI']]

    Lower95%CI  Upper95%CI
0         85.2        87.2
1         79.7        83.0
2         16.4        19.6
3         16.4        19.6
4          NaN         NaN
..         ...         ...
95        65.4        69.4
96        17.0        19.7
97         8.7        10.5
98        78.7        81.5
99        63.9        70.7

[100 rows x 2 columns]

9) Get the Year and the prevalence for the first 10 rows.

In [18]:
data.loc[:10,['Year','Prevalence']]

    Year  Prevalence
0   2014        86.2
1   2011        81.4
2   2011        17.9
3   2011        17.9
4   2010         NaN
5   2011        68.6
6   2014        24.7
7   2013        19.1
8   2010        79.1
9   2013        23.3
10  2014        64.2

10) Get the Year for the last 10 rows in the dataset.

In [32]:
list1= data.tail(5)
data.loc[95:100,['Year']]

    Year
95  2010
96  2012
97  2014
98  2012
99  2011

11) Get the Question and year for all the rows in the dataset.

In [33]:
data.loc[:,['Year','Question']]

    Year                                           Question
0   2014                          Health Insurance Coverage
1   2011                          Health Insurance Coverage
2   2011                                     Binge Drinking
3   2011                                     Binge Drinking
4   2010                                 No Personal Doctor
..   ...                                                ...
95  2010  Colon cancer screening, adults age 50+ (colono...
96  2012                                 No Personal Doctor
97  2014                    Did not get needed medical care
98  2012                          Health Insurance Coverage
99  2011  Flu shot in last 12 months, adults ages 65+ (n...

[100 rows x 2 columns]

12) Display the 3 columns from the dataset for the first 4 rows.

In [36]:
data.iloc[0:4,0:3]

  Survey                   Question  Year
0    CHS  Health Insurance Coverage  2014
1    CHS  Health Insurance Coverage  2011
2    CHS             Binge Drinking  2011
3    CHS             Binge Drinking  2011